version: "3.8"

networks:
  decet-network:
    driver: bridge

services:
  api:
    env_file:
      - .env
    container_name: decet_api
    image: mikhansan/docker-test-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    depends_on:
      - ms1
      - ms2
      - redis
      - database
    ports:
      - 3000:${API_PORT}
    expose:
      - ${API_PORT}
    networks:
      - decet-network
    restart: always

  ms1:
    env_file:
      - .env
    container_name: decet_ms1
    image: mikhansan/docker-test-ms1
    build:
      context: .
      dockerfile: ./apps/ms1/Dockerfile
    networks:
      - decet-network
    restart: always

  ms2:
    env_file:
      - .env
    container_name: decet_ms2
    image: mikhansan/docker-test-ms2
    build:
      context: .
      dockerfile: ./apps/ms2/Dockerfile
    depends_on:
      - redis
    networks:
      - decet-network
    restart: always

  redis:
    container_name: decet_redis
    image: redis:6.2.6
    command: bash -c "redis-server --appendonly yes --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    restart: always
    ports:
      - 6379:${REDIS_PORT}
    networks:
      - decet-network
    volumes:
      - ${REDIS_STORAGE}:/data

  database:
    container_name: decet_database
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:${DB_PORT}
    networks:
      - decet-network
    volumes:
      - ${DB_STORAGE}:/var/lib/postgresql/data
