version: "3"

networks:
  decet-network:
    driver: bridge

services:
  api:
    env_file:
      - .env
    container_name: decet_api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 9000:${API_PORT}
    networks:
      - decet-network
    restart: always

  ms1:
    env_file:
      - .env
    container_name: decet_ms1
    build:
      context: .
      dockerfile: ./apps/ms1/Dockerfile
    networks:
      - decet-network
    restart: always

  ms2:
    env_file:
      - .env
    container_name: decet_ms2
    build:
      context: .
      dockerfile: ./apps/ms2/Dockerfile
    networks:
      - decet-network
    restart: always
